services:
 
  redpanda:
      image: docker.redpanda.com/redpandadata/redpanda:v24.1.18
      container_name: redpanda
      command:
        - redpanda start
        - --smp 1
        - --overprovisioned
        - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
        - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
        - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
        - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
        - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
        - --rpc-addr redpanda:33145
        - --advertise-rpc-addr redpanda:33145
        - --mode dev-container
      ports:
        - 18081:18081
        - 18082:18082
        - 19092:19092
        - 19644:9644
      healthcheck:
        test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
        interval: 15s
        timeout: 3s
        retries: 5
        start_period: 5s
        
  zilla:
    image: ghcr.io/aklivity/zilla:${ZILLA_VERSION}
    container_name: zilla
    pull_policy: always
    restart: unless-stopped
    ports:
      - 7114:7114
      - 7143:7143
      - 7183:7183
      - 7883:7883
    environment:
      KEYSTORE_PASSWORD: generated
      KAFKA_BOOTSTRAP_SERVER: ${KAFKA_BOOTSTRAP_SERVER}
    volumes:
      - ../../zilla.yaml:/etc/zilla/zilla.yaml
      - ../../tls:/etc/zilla/tls
    command: start -v -e
    depends_on:
      redpanda:
        condition: service_healthy
  
  redpanda-init:
    image: docker.redpanda.com/redpandadata/redpanda:v24.1.18
    entrypoint: /bin/sh
    command:
      - "-c"
      - |
        rpk topic create --brokers redpanda:9092 mqtt-messages || exit 0;
        rpk topic create --brokers redpanda:9092 mqtt-sessions --topic-config cleanup.policy=compact
        rpk topic create --brokers redpanda:9092 mqtt-sessions --topic-config cleanup.policy=compact
        rpk topic create --brokers redpanda:9092 mqtt-retained --topic-config cleanup.policy=compact
        rpk topic create --brokers redpanda:9092 mqtt-devices --topic-config cleanup.policy=compact      
    depends_on:
      redpanda:
        condition: service_healthy
    init: true     

  mosquitto:
      image: eclipse-mosquitto
      hostname: mosquitto
      container_name: mosquitto
      restart: unless-stopped

networks:
  default:
    driver: bridge
